services:
  redpanda:
    image: redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --kafka-addr
      - 0.0.0.0:9092
      - --advertise-kafka-addr
      - 127.0.0.1:9092
    ports:
      - "9092:9092"
      - "9644:9644"
